plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\BVP\\BVP\\final\\BVPSolver\\dist"
publishOrigin = "config"
commandOrigin = "ui"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]